
services:
  php:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    volumes:
      - ./src:/var/www/html
    networks:
      - app-network

  nginx:
    build:
      context: .
      dockerfile: docker/nginx/Dockerfile
    ports:
      - "8080:80"
    volumes:
      - ./src:/var/www/html
    networks:
      - app-network
    depends_on:
      - php

  db:
    image: arm64v8/mysql
    restart: always
    environment:
      MYSQL_DATABASE: fuelphp
      MYSQL_USER: fuelphp
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: rootpassword
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3308:3306"
    networks:
      - app-network

  db_test:
    image: arm64v8/mysql
    restart: always
    environment:
      MYSQL_DATABASE: fuelphp
      MYSQL_USER: fuelphp
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: rootpassword
    volumes:
      - db_data_test:/var/lib/mysql
    ports:
      - "3309:3306"
    networks:
      - app-network

volumes:
  db_data:
  db_data_test:
  
networks:
  app-network: